# Generated by Django 3.2.12 on 2022-07-12 17:17

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_encrypted_model_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemodel',
            name='json_encrypted',
            field=encrypted_model_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='samplemodel',
            name='json_plain',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
