# Generated by Django 3.2.12 on 2022-07-15 15:53

from django.db import migrations, models
import encrypted_json_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_encrypted', encrypted_json_fields.fields.EncryptedCharField(blank=True, default='Sample text')),
                ('json_encrypted', encrypted_json_fields.fields.EncryptedJSONField(blank=True, default={'bool_value': True, 'dict_value': {'aaa': 'AAA', 'bbb': 'BBB', 'inner': {'one': 1, 'two': 2}}, 'float_value': 123.45, 'int_value': 123, 'list_value': [1, 2, 'three', False, 5.0], 'str_value': 'text'})),
            ],
        ),
    ]
